### PR TITLE
Issue#271: Fix refactored phpunit_util causing unit test error

### PR DESCRIPTION
**Pull request by SashaAnastasi**

### CODE REVIEW

**Comment by tuanngocnguyen** [comment]
Hi @SashaAnastasi Thanks for your works.

Would you please use these functions instead:
        $this->getDebuggingMessages();
        $this->resetDebugging();
as  \core_phpunit\internal_util only exists on Totara.

**Comment by SashaAnastasi** [comment]
Hi @tuanngocnguyen I have done this.

**Comment by tuanngocnguyen** [comment]
Hi @SashaAnastasi 

Thanks for your changes.
Would you please also change the target branch to Moodle 39 STABLE (for Totara 13+)?
You can find the supported branch here (readme.md):

https://github.com/catalyst/moodle-auth_outage

**Comment by tuanngocnguyen** [comment]
I am closing this issue as the fix has been applied on Moodle 39 STABLE

**Pull request closed without merging**
