### PR TITLE
Moodle 3.10 and Totara 13 fixes for PHPUnit 9

### PR DESCRIPTION
**Pull request by ScottVerbeek**

### CODE REVIEW

**Comment by danmarsden** [comment]
Just dropping a note on this one too. I think using version 1-3 naming is wrong. It does not follow moodle conventions and may cause problems in future. Happy to discuss further next week!

One example of it being problematic...

Typically number versioning suggests the latest version (3) is the latest release. In this proposed scenario Totara sites will likely never be 'upgraded' to version 3 and in fact may be stuck on 2... although what happens when we need to branch again for totara14 ? We cant use v3 so do we have a 2.5 ?

**Comment by ScottVerbeek** [comment]
> Just dropping a note on this one too. I think using version 1-3 naming is wrong. It does not follow moodle conventions and may cause problems in future. Happy to discuss further next week!
> 
> One example of it being problematic...
> 
> Typically number versioning suggests the latest version (3) is the latest release. In this proposed scenario Totara sites will likely never be 'upgraded' to version 3 and in fact may be stuck on 2... although what happens when we need to branch again for totara14 ? We cant use v3 so do we have a 2.5 ?

I have changed to the way the plugin currently handles this. And have added the commits required.

**Comment by ScottVerbeek** [comment]
When merging this, https://github.com/catalyst/moodle-auth_outage/pull/225 and https://github.com/catalyst/moodle-auth_outage/pull/228 should be ,merged as well.

**Comment by danmarsden** [comment]
closing this one as it conflicts - has some patches that have already been merged into master - will deal with the phpunit fixes separately.

**Pull request closed without merging**
