### PR TITLE
Accept unix time for --start CLI option to MOODLE_32_STABLE branch

### PR DESCRIPTION
**Pull request by ledship**
From #167

### CODE REVIEW

**Comment by brendanheywood** [comment]
@ledship are you able to look into the travis failures? (which might be unrelated)

**Comment by ledship** [comment]
Looks unrelated

php5.5 tests fail because the url to download php5.5 returns 404
On the php7.0 tests it downloads successfully but fails to create the database because it can't connect to postgres

**Comment by ledship** [comment]
@brendanheywood I've fixed the travis config in #205 which should resolve the failing check here.

**Comment by brendanheywood** [comment]
cool, does this need a rebase then?

**Comment by ledship** [comment]
@brendanheywood rebased and passing tests

**Pull request merged**
